# Array creation by conversion from other python structures

In [1]:
import numpy as np

1d array, the second parameter is optional we can customize the size of our stored datatypes

In [38]:
arr = np.array([67,12,45,89], np.int32)

2d array 

In [41]:
myarr = np.array([[2,34,98], [6,1,89], [7,9,24]])

In [42]:
myarr

array([[ 2, 34, 98],
       [ 6,  1, 89],
       [ 7,  9, 24]])

In [32]:
myarr.shape

(1, 4)

updating a value inside a 2d array

In [40]:
myarr[0,1] = 45

In [36]:
myarr.dtype

dtype('int32')

In [44]:
myarr.size

9

array creation of object type

In [45]:
np.array({5,1,3})

array({1, 3, 5}, dtype=object)

# Intrinsic numpy array creation objects

array containing zeros with size 2 rows and 14 columns 

In [49]:
zero = np.zeros((2,14))

In [50]:
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

0 to n-1 numbers in an array

In [52]:
rng = np.arange(15)

In [53]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array with 20 numbers from 1 to 5 with same amount of diff with any to consecutive element

In [56]:
lspace = np.linspace(1,5,20)

In [57]:
lspace

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

empty array of size 4,4 with random values

In [64]:
emp = np.empty((4,4))

In [65]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78020169e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

empty array with values and size of lspace array

In [68]:
empl = np.empty_like(lspace)

In [69]:
empl

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

identity matrix of size 12 X 12

In [70]:
ide = np.identity(12)

In [71]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

reshaping aa 1d array to 2d array but overall size should be same

In [72]:
arr2 = np.arange(15)

In [73]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
arr2 = arr2.reshape(5,3)

In [77]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [78]:
arr2.shape

(5, 3)

In [103]:
arr2 = arr2.ravel()

In [104]:
arr2.shape

(15,)

In [105]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# the total number of axis of a numpy array is same as its dimension

In [107]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [108]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [109]:
ax = np.array(x)

In [110]:
ax

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

0th axis is towards rows and 1st axis is towards columns

sum of all elemnts in 0th axis

In [112]:
ax.sum(axis=0)

array([12, 15, 18])

sum of all elemnts in 1st axis

In [113]:
ax.sum(axis=1)

array([ 6, 15, 24])

transposing 2d matrix

In [114]:
ax.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [115]:
ax

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

it gives you an iterator

In [119]:
ax.flat

In [120]:
for i in ax.flat:
    print(i)

1
2
3
4
5
6
7
8
9


it tells us the number of dimensions of our array

In [123]:
ax.ndim

2

In [124]:
ax.size

9

total bytes our array consumed

In [126]:
ax.nbytes

36

In [132]:
app = np.array([1,2,54,61,0,12,34,4])

arg methods gives us indexes

index with max value

In [130]:
app.argmax()

3

index with min value

In [133]:
app.argmin()

4

order of indexes of our sorted array

In [134]:
app.argsort()

array([4, 0, 1, 7, 5, 6, 2, 3], dtype=int64)

for 2d arrays it makes the array 1d and then gives us the index

In [136]:
ax.argmax()

8

In [137]:
ax.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [138]:
ax.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [139]:
ax.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [140]:
ax.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [141]:
ax.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

it gives the following array in 1d

In [156]:
ax.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
ax.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [158]:
ax

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
myarr

array([[ 2, 34, 98],
       [ 6,  1, 89],
       [ 7,  9, 24]])

add the matrix element by element

In [165]:
ax + myarr

array([[  3,  36, 101],
       [ 10,   6,  95],
       [ 14,  17,  33]])

In [166]:
ax * myarr

array([[  2,  68, 294],
       [ 24,   5, 534],
       [ 49,  72, 216]])

gives array of square root of the elements inside the array

In [170]:
np.sqrt(myarr)

array([[1.41421356, 5.83095189, 9.89949494],
       [2.44948974, 1.        , 9.43398113],
       [2.64575131, 3.        , 4.89897949]])

In [171]:
ax.sum()

45

In [172]:
ax.max()

9

In [173]:
ax.min()

1

In [174]:
np.where(ax>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [175]:
ax

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

gives tuple which contains array of indexes for every axis where elements are greater than 5

In [192]:
np.where(myarr>5)

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 2, 0, 1, 2], dtype=int64))

In [184]:
myarr

array([[ 2, 34, 98],
       [ 6,  1, 89],
       [ 7,  9, 24]])

counts of non zeros

In [194]:
np.count_nonzero(ax)

9

In [195]:
np.nonzero(ax)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [196]:
import sys 

In [212]:
py_ar = [8,6,7,5]

In [213]:
np_ar = np.array(py_ar)

In [214]:
sys.getsizeof(1) * len(py_ar)

112

In [215]:
np_ar.itemsize * np_ar.size

16